#! /usr/bin/env python
# encoding: utf-8

import shutil, subprocess, os

def options(opt):
    pass

def configure(conf):
    subprocess.check_call('opam update',shell=True)

def build(bld):
    bld(rule = 'opam install -y electrod')

def distclean(ctx):
    pass

def sourceclean(ctx):
    pass