#! /usr/bin/env python
# encoding: utf-8

import shutil, subprocess, os

def options(opt):
    pass

def configure(conf):
    subprocess.check_call('opam update',shell=True)

def build(bld):
    bld(rule = 'opam install -y electrod --destdir ' + bld.path.abspath() + '/electrod')
    
    bld.install_files('${LIBDIR}', 'electrod/bin/electrod', chmod=493)

def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    shutil.rmtree(ctx.path.abspath() + '/electrod', True)

def sourceclean(ctx):
    pass