#! /usr/bin/env python
# encoding: utf-8

import shutil, subprocess, os

LINGELING = 'lingeling-ayv-86bf266-140429'

def options(opt):
    opt.load('compiler_c')
    opt.load('java')

def configure(conf):
    conf.load('compiler_c')
    conf.load('java')
    conf.check_jni_headers()
    sourceclean(conf)
    root = conf.path.abspath()
    subprocess.check_call(['wget', 'http://fmv.jku.at/lingeling/' + LINGELING + '.zip', '--directory-prefix', root])
    subprocess.check_call(['unzip', root + '/' + LINGELING + '.zip','code/*', '-d', root])

def build(bld):
    DEFINES = ['NDBLSCR', 'NLGLOG','NDEBUG', 'NCHKSOL', 'NLGLPICOSAT', 'NLGLDRUPLIG', 'NLGLYALSAT']
    CFLAGS = ['-w', '-O3', '-fPIC']
    INCLUDES = ['.']
    
    # Build x64 
    bld.objects(source = 'code/lglib.c',
                target = 'lglib-x64', arch = 'x86_64',
                includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)    
    bld.shlib(source = 'kodkod_engine_satlab_Lingeling.c',
              target = 'lingeling-x64', arch = 'x86_64',
              use = 'lglib-x64', uselib = 'JAVA',
              includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)

    # Build arm64 
    bld.objects(source = 'code/lglib.c',
                target = 'lglib-arm64', arch = 'arm64',
                includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)    
    bld.shlib(source = 'kodkod_engine_satlab_Lingeling.c',
              target = 'lingeling-arm64', arch = 'arm64',
              use = 'lglib-arm64', uselib = 'JAVA',
              includes = INCLUDES, cflags = CFLAGS, defines = DEFINES)

    # Build universal dylib
    bld(rule='lipo -create -output ${TGT} ${SRC}',
        use='lingeling-arm64 lingeling-x64',
        target='liblingeling.dylib',
        source='liblingeling-arm64.dylib liblingeling-x64.dylib') 


def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    sourceclean(ctx)

def sourceclean(ctx):
    shutil.rmtree(ctx.path.abspath() + '/code', True)
    try:
        os.remove(ctx.path.abspath() + '/' + LINGELING + '.zip')
    except OSError:
        pass
