#! /usr/bin/env python
# encoding: utf-8

import shutil
import subprocess

def options(opt):
    opt.load('compiler_cxx')
    opt.load('java')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('java')
    conf.check_jni_headers()
    MINISAT = conf.path.abspath() + '/minisat'
    shutil.rmtree(MINISAT, True)
    subprocess.check_call(['git', 'clone', 'https://github.com/stp/minisat.git', MINISAT])


def build(bld):
    DEFINES = ['__STDC_LIMIT_MACROS', '__STDC_FORMAT_MACROS']
    INCLUDES = ['.','./minisat'] 
    CXXFLAGS = [ '-w', '-O3', '-fPIC']
    
    # Build for ARM64
    bld.objects(source = ['minisat/minisat/utils/Options.cc', 'minisat/minisat/utils/System.cc'],
                target = 'minisat-utils-arm64', arch = 'arm64',
                includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)    
    bld.objects(source = 'minisat/minisat/core/Solver.cc',
                target = 'minisat-core-arm64', use = 'minisat-utils-arm64', arch = 'arm64',
                includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)    
    bld.shlib(source = 'kodkod_engine_satlab_MiniSat.cpp',
              target = 'minisat-arm64', use = 'minisat-core-arm64', uselib = 'JAVA', arch = 'arm64',
              includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)

    # Build for X86
    bld.objects(source = ['minisat/minisat/utils/Options.cc', 'minisat/minisat/utils/System.cc'],
                target = 'minisat-utils-x64', arch = 'x86_64',
                includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)    
    bld.objects(source = 'minisat/minisat/core/Solver.cc',
                target = 'minisat-core-x64', use = 'minisat-utils-x64', arch = 'x86_64',
                includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)    
    bld.shlib(source = 'kodkod_engine_satlab_MiniSat.cpp',
              target = 'minisat-x64', use = 'minisat-core-x64', uselib = 'JAVA', arch = 'x86_64',
              includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)
    
    # Build universal dylib
    bld(rule='lipo -create -output libminisat.dylib libminisat-x64.dylib libminisat-arm64.dylib', always=True)            

def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    shutil.rmtree(ctx.path.abspath() + '/minisat', True)
    
    
