#! /usr/bin/env python
# encoding: utf-8

import shutil
import subprocess

def options(opt):
    opt.load('compiler_cxx')
    opt.load('java')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('java')
    conf.check_jni_headers()
    MINISAT = conf.path.abspath() + '/minisatp'
    shutil.rmtree(MINISAT, True)
    subprocess.check_call(['git', 'clone', 'https://github.com/emina/minisatp.git', MINISAT])
 
def build(bld):
    DEFINES = ['__STDC_LIMIT_MACROS', '__STDC_FORMAT_MACROS']
    INCLUDES = ['.', './minisatp'] 
    CXXFLAGS = [ '-w', '-O3', '-fPIC', '-ffloat-store']
    
    # build for arm64
    bld.objects(source = ['minisatp/Solver.C', 'minisatp/Proof.C', 'minisatp/File.C'],
                target = 'minisatp-core-arm64', arch = 'arm64',
                includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)
    bld.shlib(source = 'kodkod_engine_satlab_MiniSatProver.cpp',
              target = 'minisatprover-arm64', use = 'minisatp-core-arm64', uselib = 'JAVA', arch = 'arm64',
              includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)

    # Build for x64
    bld.objects(source = ['minisatp/Solver.C', 'minisatp/Proof.C', 'minisatp/File.C'],
                target = 'minisatp-core-x64', arch = 'x86_64',
                includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)
    bld.shlib(source = 'kodkod_engine_satlab_MiniSatProver.cpp',
              target = 'minisatprover-x64', use = 'minisatp-core-x64', uselib = 'JAVA', arch = 'x86_64',
              includes = INCLUDES, cxxflags = CXXFLAGS, defines = DEFINES)
    
    # Build universal dylib (need to give *use* to make sure this comes last in build order, but 
    #   also need to give the file names, not the target names above, in target. Don't conflate 
    #   the target and use properties)
    bld(rule='lipo -create -output ${TGT} ${SRC}',
        use='minisatprover-arm64 minisatprover-x64',
        target='libminisatprover.dylib',
        source='libminisatprover-arm64.dylib libminisatprover-x64.dylib') 


def distclean(ctx):
    from waflib import Scripting
    Scripting.distclean(ctx)
    shutil.rmtree(ctx.path.abspath() + '/minisatp', True)
    

    
    
